# Generated by Django 2.0.1 on 2018-01-17 01:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0003_auto_20180115_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackTeamInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('access_token', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
                ('bot_user_id', models.CharField(max_length=255)),
                ('bot_access_token', models.CharField(max_length=255)),
                ('installer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack.SlackUser')),
                ('slack_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack.SlackTeam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlackTeamSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('slack_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack.SlackTeam')),
            ],
        ),
        migrations.RemoveField(
            model_name='slacksettings',
            name='slack_team',
        ),
        migrations.DeleteModel(
            name='SlackSettings',
        ),
        migrations.AlterUniqueTogether(
            name='slackteamsetting',
            unique_together={('slack_team', 'name')},
        ),
    ]
