# Generated by Django 2.0.1 on 2018-01-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0005_slackteamsetting_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackteamsetting',
            old_name='type',
            new_name='data_type',
        ),
    ]
