# Generated by Django 2.0.2 on 2018-02-01 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='original_poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asked_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(related_name='topics', to='topics.Tag'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='participants',
            field=models.ManyToManyField(related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
    ]
