# Generated by Django 2.0.1 on 2018-01-11 01:08

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 11, 1, 8, 47, 283804)),
        ),
    ]
