# Generated by Django 2.0.2 on 2018-02-09 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20180201_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='original_poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
