# Generated by Django 2.0.1 on 2018-01-24 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20180117_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
