# Generated by Django 2.0.1 on 2018-01-25 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_auto_20180124_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='participants',
            field=models.ManyToManyField(related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
    ]
