# Generated by Django 2.0.1 on 2018-01-27 00:05

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_auto_20180125_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='is_solved',
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=django_fsm.FSMField(default='UNSOLVED', max_length=50, protected=True),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=django_fsm.FSMField(default='OPEN', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(related_name='topics', to='topics.Tag'),
        ),
    ]
