# Generated by Django 2.0.1 on 2018-01-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_auto_20180125_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(related_name='topics', to='topics.Tag'),
        ),
    ]
