# Generated by Django 2.0.1 on 2018-01-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_auto_20180127_0005'),
        ('topics', '0009_auto_20180126_0104'),
    ]

    operations = [
    ]
