# Generated by Django 2.0.1 on 2018-01-11 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0003_auto_20180111_0146'),
        ('groups', '0002_auto_20180111_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('discussion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.Discussion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlackSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('bot_token', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Slack Settings',
            },
        ),
        migrations.CreateModel(
            name='SlackTeam',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('real_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('avatar_72', models.CharField(max_length=255)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('slack_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack_integration.SlackTeam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='slacksettings',
            name='slack_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slack_integration.SlackTeam'),
        ),
        migrations.AddField(
            model_name='slackchannel',
            name='slack_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack_integration.SlackTeam'),
        ),
    ]
