# Generated by Django 2.0.1 on 2018-01-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0002_auto_20180115_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackevent',
            old_name='timestamp',
            new_name='ts',
        ),
    ]
