# Generated by Django 2.0.2 on 2018-02-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0002_auto_20180201_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackagent',
            old_name='discuss_channel_id',
            new_name='topic_channel_id',
        ),
    ]
