# Generated by Django 2.0.2 on 2018-02-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0003_auto_20180207_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackuser',
            old_name='avatar_72',
            new_name='image_72',
        ),
        migrations.AlterField(
            model_name='slackchannel',
            name='discussion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slack_channel', to='topics.Discussion'),
        ),
    ]
