# Generated by Django 2.0.1 on 2018-01-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0006_auto_20180117_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slackteamsetting',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='slackteamsetting',
            name='slack_team',
        ),
        migrations.DeleteModel(
            name='SlackTeamSetting',
        ),
    ]
