# Generated by Django 2.0.1 on 2018-01-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0007_auto_20180123_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackuser',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
