# Generated by Django 2.0.1 on 2018-01-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0008_slackuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackteaminstallation',
            name='help_channel_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
