# Generated by Django 2.0.1 on 2018-01-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0009_slackteaminstallation_help_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackteaminstallation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
