# Generated by Django 2.0.1 on 2018-01-25 19:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20180123_0115'),
        ('slack_integration', '0012_auto_20180125_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('INITIATED', 'INITIATED'), ('AUTHENTICATED', 'AUTHENTICATED'), ('ACTIVE', 'ACTIVE'), ('PAUSED', 'PAUSED'), ('DEACTIVATED', 'DEACTIVATED')], default='INITIATED', max_length=14)),
                ('help_channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_agent', to='groups.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='slackapplicationinstallation',
            name='help_channel_id',
        ),
        migrations.RemoveField(
            model_name='slackapplicationinstallation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='slackapplicationinstallation',
            name='slack_team',
        ),
        migrations.RemoveField(
            model_name='slackteam',
            name='group',
        ),
        migrations.AlterField(
            model_name='slackapplicationinstallation',
            name='installer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='slack_integration.SlackUser'),
        ),
        migrations.AddField(
            model_name='slackapplicationinstallation',
            name='slack_agent',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slack_application_installation', to='slack_integration.SlackAgent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slackteam',
            name='slack_agent',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slack_team', to='slack_integration.SlackAgent'),
            preserve_default=False,
        ),
    ]
