# Generated by Django 2.0.1 on 2018-01-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0013_auto_20180125_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackapplicationinstallation',
            name='slack_agent',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='slack_application_installation', to='slack_integration.SlackAgent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slackteam',
            name='slack_agent',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='slack_team', to='slack_integration.SlackAgent'),
            preserve_default=False,
        ),
    ]
