# Generated by Django 2.0.1 on 2018-01-25 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0014_auto_20180125_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackagent',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'INITIATED'), ('AUTHENTICATED', 'AUTHENTICATED'), ('ACTIVE', 'ACTIVE'), ('PAUSED', 'PAUSED'), ('INACTIVE', 'INACTIVE')], default='INITIATED', max_length=14),
        ),
        migrations.AlterField(
            model_name='slackapplicationinstallation',
            name='installer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='slack_integration.SlackUser'),
            preserve_default=False,
        ),
    ]
