# Generated by Django 2.0.1 on 2018-01-25 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0015_auto_20180125_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackagent',
            name='id',
        ),
        migrations.AlterField(
            model_name='slackagent',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='slack_agent', serialize=False, to='groups.Group'),
        ),
    ]
