# Generated by Django 2.0.1 on 2018-01-26 22:53

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0016_auto_20180125_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackagent',
            name='status',
            field=django_fsm.FSMField(default='INITIATED', max_length=50, protected=True),
        ),
    ]
