# Generated by Django 2.0.1 on 2018-01-11 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20180111_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 11, 14, 55, 50, 984486, tzinfo=utc)),
        ),
    ]
