# Generated by Django 2.0.2 on 2018-02-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
