# Generated by Django 2.0.1 on 2018-01-25 13:51

import app.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180111_1445'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.users.managers.CustomUserManager()),
            ],
        ),
    ]
