# Generated by Django 2.0.1 on 2018-01-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0002_auto_20180115_1844'),
        ('dialogues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
        migrations.AddField(
            model_name='message',
            name='slack_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slack_integration.SlackEvent'),
        ),
        migrations.AddField(
            model_name='reply',
            name='slack_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slack_integration.SlackEvent'),
        ),
    ]
