# Generated by Django 2.0.1 on 2018-01-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogues', '0003_auto_20180116_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='slack_event',
            new_name='origin_slack_event',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='slack_event',
            new_name='origin_slack_event',
        ),
    ]
