# Generated by Django 2.0.1 on 2018-01-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsettings',
            options={'verbose_name_plural': 'Group Settings'},
        ),
    ]
