# Generated by Django 2.0.1 on 2018-01-17 01:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20180111_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupsettings',
            name='group',
        ),
        migrations.DeleteModel(
            name='GroupSettings',
        ),
        migrations.AlterUniqueTogether(
            name='groupsetting',
            unique_together={('group', 'name')},
        ),
    ]
