# Generated by Django 2.0.1 on 2018-01-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20180117_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupsetting',
            old_name='datatype',
            new_name='data_type',
        ),
    ]
