# Generated by Django 2.0.1 on 2018-01-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20180117_1403'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupsetting',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='groupsetting',
            name='group',
        ),
        migrations.DeleteModel(
            name='GroupSetting',
        ),
    ]
